/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
  publicPath: '/build/',
  serverBuildPath: 'api/index.js',
  serverMainFields: ['main', 'module'],
  serverModuleFormat: 'cjs',
  serverPlatform: 'node',
  serverMinify: false,
  // When running locally in development mode, we use the built in remix
  // server. This does not understand the vercel lambda module format,
  // so we default back to the standard build output.
  server: process.env.NODE_ENV === 'development' ? undefined : './server.js',
  ignoredRouteFiles: ['**/.*'],
  appDirectory: 'app',
  assetsBuildDirectory: 'public/build',
  serverDependenciesToBundle: [
    /^rehype.*/,
    /^remark.*/,
    /^unified.*/,
    /^unist.*/,
    /^hast-.*/,
    /^mdast-.*/,
    /^micromark-.*/,
    /^character-.*/,
    'bail',
    'is-plain-obj',
    'trough',
    'zwitch',
    'nanoid',
    'node-fetch',
    /^vfile.*/,
    /^myst.*/,
    /^@myst-theme.*/,
    '@curvenote/common',
    '@curvenote/cdn',
    'tex-to-typst',
    'jats-tags',
    'doi-utils',
    'simple-validators',
    'credit-roles',
    'orcid',
    'markdown-it-myst',
    'html-whitespace-sensitive-tag-names',
    'array-iterate',
    'property-information',
    'html-void-elements',
    'hastscript',
    'web-namespaces',
    'stringify-entities',
    'ccount',
    'comma-separated-tokens',
    'space-separated-tokens',
    'trim-trailing-lines',
    'escape-string-regexp',
    'trim-lines',
    '@curvenote/icons',
    'react-syntax-highlighter',
  ],
  watchPaths: [],
  future: {
    v2_routeConvention: true,
    v2_normalizeFormMethod: true,
  },
};
